# Generated by Django 5.1.1 on 2025-02-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='diss_like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
