# Generated by Django 5.1.1 on 2025-01-29 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0005_alter_dislike_user_alter_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percentage', models.PositiveIntegerField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='product_module.product')),
            ],
            options={
                'verbose_name': 'ProductDiscount',
                'verbose_name_plural': 'ProductDiscounts',
                'db_table': 'ProductDiscount_DB',
            },
        ),
    ]
