# Generated by Django 5.1.1 on 2025-01-29 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_module', '0001_initial'),
        ('product_module', '0005_alter_dislike_user_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='product_module.product'),
        ),
    ]
