# Generated by Django 5.1.1 on 2025-02-07 18:35

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branddiscount',
            managers=[
                ('now_until_end_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='categorydiscount',
            managers=[
                ('now_until_end_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productdiscount',
            managers=[
                ('now_until_end_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
