# Generated by Django 5.1.1 on 2025-02-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_activate',
        ),
    ]
