# Generated by Django 5.1.1 on 2024-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_user_email_activate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(db_index=True, max_length=11, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/avatar'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User_DB',
        ),
    ]
