# Generated by Django 5.1.1 on 2024-10-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_alter_user_options_alter_user_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
